naming:
  FunctionNaming:
    active: true
    ignoreAnnotated: [ 'Composable' ]
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/androidUnitTest/**'
      - '**/androidInstrumentedTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
    functionPattern: '[a-z][a-zA-Z0-9]*'
    excludeClassPattern: '$^'

style:
  UnusedPrivateMember:
    active: true
    allowedNames: ''
    ignoreAnnotated: [ 'Preview' ]

  MaxLineLength:
    active: false

complexity:
  LongMethod:
    threshold: 80